# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fb8f4ac19b58128e5de9a03be57cc8641ca7a6e68d940fa00d5d6f7bbc84c92754ca2c729bcd90fa4e25ebe5b8693b5a22dd1146788c1f83be9fb8f93c7a3d5

test:
  secret_key_base: 5676dfc71426756541b69677aaa3fe76fd1511f88929c35a190781c1106bbe01be46f286d7e114156733df980f0c8381106d3ad770357253b445d700ec30f604

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
